/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScannerRouteImport } from './routes/_app.scanner'
import { Route as AppParcoursRouteImport } from './routes/_app.parcours'
import { Route as AppEvenementsRouteImport } from './routes/_app.evenements'
import { Route as AppCreerRouteImport } from './routes/_app.creer'
import { Route as AppAccueilRouteImport } from './routes/_app.accueil'
import { Route as AppAccesRouteImport } from './routes/_app.acces'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppParcoursRoute = AppParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => AppRoute,
} as any)
const AppEvenementsRoute = AppEvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => AppRoute,
} as any)
const AppCreerRoute = AppCreerRouteImport.update({
  id: '/creer',
  path: '/creer',
  getParentRoute: () => AppRoute,
} as any)
const AppAccueilRoute = AppAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AppRoute,
} as any)
const AppAccesRoute = AppAccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acces': typeof AppAccesRoute
  '/accueil': typeof AppAccueilRoute
  '/creer': typeof AppCreerRoute
  '/evenements': typeof AppEvenementsRoute
  '/parcours': typeof AppParcoursRoute
  '/scanner': typeof AppScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acces': typeof AppAccesRoute
  '/accueil': typeof AppAccueilRoute
  '/creer': typeof AppCreerRoute
  '/evenements': typeof AppEvenementsRoute
  '/parcours': typeof AppParcoursRoute
  '/scanner': typeof AppScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/acces': typeof AppAccesRoute
  '/_app/accueil': typeof AppAccueilRoute
  '/_app/creer': typeof AppCreerRoute
  '/_app/evenements': typeof AppEvenementsRoute
  '/_app/parcours': typeof AppParcoursRoute
  '/_app/scanner': typeof AppScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/acces'
    | '/accueil'
    | '/creer'
    | '/evenements'
    | '/parcours'
    | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/acces'
    | '/accueil'
    | '/creer'
    | '/evenements'
    | '/parcours'
    | '/scanner'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/acces'
    | '/_app/accueil'
    | '/_app/creer'
    | '/_app/evenements'
    | '/_app/parcours'
    | '/_app/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parcours': {
      id: '/_app/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof AppParcoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evenements': {
      id: '/_app/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof AppEvenementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creer': {
      id: '/_app/creer'
      path: '/creer'
      fullPath: '/creer'
      preLoaderRoute: typeof AppCreerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accueil': {
      id: '/_app/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AppAccueilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acces': {
      id: '/_app/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AppAccesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccesRoute: typeof AppAccesRoute
  AppAccueilRoute: typeof AppAccueilRoute
  AppCreerRoute: typeof AppCreerRoute
  AppEvenementsRoute: typeof AppEvenementsRoute
  AppParcoursRoute: typeof AppParcoursRoute
  AppScannerRoute: typeof AppScannerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccesRoute: AppAccesRoute,
  AppAccueilRoute: AppAccueilRoute,
  AppCreerRoute: AppCreerRoute,
  AppEvenementsRoute: AppEvenementsRoute,
  AppParcoursRoute: AppParcoursRoute,
  AppScannerRoute: AppScannerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
